spring:
  thymeleaf:
    #关闭缓存
    cache: false
    #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 262518
    #springboot默认最快的连接池
    hikari:
      #连接池名
      pool-name: DataHikariCp
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最长时间 默认为10分钟（60000）
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认为30分钟（180000）
      max-lifetime: 180000
      #连接超时时间，默认为30000
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml配置文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #mybatis数据返回的别名
  type-aliases-package: com.gjw.seckill.pojo
#Mybatis SQL打印（方法接口所在包）
logging:
  level:
    com.gjw.seckill.mapper: debug
